# Generated by Django 4.2.3 on 2023-09-07 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_App', '0003_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_two',
            field=models.ImageField(blank=True, null=True, upload_to='product_image'),
        ),
    ]
