# Generated by Django 4.2.3 on 2023-09-02 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='name',
            new_name='first_name',
        ),
    ]
