# Generated by Django 4.2.3 on 2023-09-06 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_App', '0006_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.CharField(max_length=500)),
            ],
        ),
    ]
