# Generated by Django 4.2.3 on 2023-09-08 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_App', '0007_enquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('ORDER CORNFIMED', 'ORDER CORNFIMED'), ('SHIPPED', 'SHIPPED'), ('ORDER DONE', 'ORDER DONE')], default='PENDING', max_length=100),
        ),
    ]
