# Generated by Django 4.2.3 on 2023-09-15 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_App', '0010_alter_order_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_espected',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
