# Generated by Django 4.2.3 on 2023-09-15 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_App', '0011_alter_order_delivery_espected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_of_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
